version: "3"
services:
  api:
    image: transitorykris/geoful
    environment:
      - APP_ASN_DATA=/data/GeoIPASNum.dat
      - 'APP_BIND=:8001'
      - APP_COUNTRY_DATA=/data/GeoIP.dat
    ports:
      - '8001:8001'
    networks:
      - geoful
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

networks:
  geoful:
    driver: overlay
    ipam:
      config:
        - subnet: 10.1.1.0/24
